version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8088:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
