# Use the official Node.js image as a base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Set environment variable for Node options
# ENV NODE_OPTIONS=--openssl-legacy-provider

# Command to run the application
CMD ["ng", "serve", "--host", "0.0.0.0"]
