# Use the official Node.js image as a base image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy the rest of the application code
COPY . .

# Copy the environment template file
COPY src/environments/environment.template.ts src/environments/environment.template.ts

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext-base

# Replace environment variables in the template
CMD ["/bin/sh", "-c", "envsubst < src/environments/environment.template.ts > src/environments/environment.ts && ng serve --host 0.0.0.0"]

# Expose the port the app runs on
EXPOSE 4200