version: '3.8'

services:
  angular-app-prod:
    container_name: 'angular-service-prod'
    build:
      context: .
      dockerfile: Dockerfile.prod.env
      args:
        API_URL: ${API_URL}
    ports:
      - "8088:8080"
    networks:
      - pbxswitch-net
    environment:
      #- API_URL=http://dev-ectl.cloud-connect.in:3000/
      - API_URL=http://angular-api-service:3000/

networks:
  pbxswitch-net:
    external: true
    name: pbxswitch-net