version: '3.7'

services:
  angular-service:
    container_name: 'angular-service'
    build:
      context: .
      dockerfile: Dockerfile.dev.env
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

      # Call Development Server
      #- API_URL=http://dev-ectl.cloud-connect.in:3000/

      # No Proxy direct call localhost:3000
      #- API_URL=http://localhost:3000/api/

      # For Proxy
      - API_URL=/api/
    networks:
      - pbxswitch-net

volumes:
  node_modules:

networks:
  pbxswitch-net:
    external: true
    name: pbxswitch-net